NetCore-Docker-Easy/Models/Database/FilmDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace NetCore_Docker_Easy.Models
{
    public class FilmDbContext : DbContext
    {
        public FilmDbContext(DbContextOptions<FilmDbContext> options) : base(options) { }

        public DbSet<Film> Film { get; set; }
    }
}

NetCore-Docker-Easy/Models/ErrorViewModel.cs
namespace NetCore_Docker_Easy.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCore-Docker-Easy/Models/Film.cs
using System.ComponentModel.DataAnnotations;

namespace NetCore_Docker_Easy.Models
{
    public class Film
    {
        [Required]
        public int ReleaseYear { get; set; } = 1970;

        [Required]
        [Key]
        public int No { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Movie name cannot exceed 50 characters.")]
        public string MovieName { get; set; } = string.Empty;
    }
}

NetCore-Docker-Easy/Controllers/FilmController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using NetCore_Docker_Easy.Models;
using NetCore_Docker_Easy.Services;

namespace NetCore_Docker_Easy.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmService _filmService;

        public FilmController(IFilmService filmService)
        {
            _filmService = filmService;
        }

        [HttpPost]
        public async Task<IActionResult> Create(Film flm)
        {
            if (ModelState.IsValid)
            {                
                await _filmService.Add(flm);
                return RedirectToAction(nameof(Index));
            }
            else
                return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(Film flm)
        {
            if (ModelState.IsValid)
            {
                await _filmService.Update(flm);
                return RedirectToAction(nameof(Index));
            }
            else
                return View(flm);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            await _filmService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }
        public async Task<IActionResult> Update(int id)
        {
            var del = await _filmService.Get(id);
            return View(del);
        }
        public async Task<IActionResult> Index()
        {
            var flm = await _filmService.Get();
            return View(flm);
        }
    }
}

NetCore-Docker-Easy/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetCore_Docker_Easy.Models;
using System.Diagnostics;

namespace NetCore_Docker_Easy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCore-Docker-Easy/Views/Film/Create.cshtml
@model Film

@{
    ViewData["Title"] = "Add a New Movie";
}

<div class="row m-4">
    <div class="column">
        <h1 class="text-dark">Add a New Movie</h1>
    </div>
</div>

<div class="row m-4">
    <div class="row m-2">
        <div class="column col-3">
            <a class="btn btn-outline-info" asp-action="Index">Show all Movies</a>
        </div>
    </div>

    <div class="row m-2">
        <div class="column col-4">
            <form enctype="application/x-www-form-urlencoded" method="post">
                <div class="form-group m-2">
                    <label for="movieName">Movie Name</label>
                    <input type="text" class="form-control" id="movieName" asp-for="MovieName" placeholder="Star Wars: Episode IV - A New Hope">
                </div>
                <div class="form-group m-2">
                    <label for="movieYear">Release Year</label>
                    <input type="number" class="form-control" id="movieYear" asp-for="ReleaseYear" placeholder="1977">
                </div>
                <div class="row m-2">
                    <input type="submit" class="btn btn-secondary" value="Add New" />
                </div>
            </form>
        </div>
    </div>
    
    <div class="row">
        <div class="text-danger" asp-validation-summary="All"></div>
    </div>
</div>

NetCore-Docker-Easy/Views/Film/Index.cshtml
@model List<Film>

@{
    ViewData["Title"] = "Movies Release Years";
}

<div class="row m-4">
    <div class="column">
        <h1 class="text-dark">Movies Release Years</h1>
    </div>
</div>

<div class="row m-4">
    <div class="row m-2">
        <div class="column col-3">
            <a class="btn btn-outline-success" asp-action="Create">Add a New Movie</a>
        </div>
    </div>
    <div class="row m-2">
        <table class="table">
            <tr>
                <th>S#</th>
                <th>Movie Name</th>
                <th>Release Year</th>
                <th></th>
                <th></th>
            </tr>
            @if (Model?.Any() == true)
            {
                foreach (Film flm in Model)
                {
                    <tr>
                        <td>@flm.No</td>
                        <td>@flm.MovieName</td>
                        <td>@flm.ReleaseYear</td>
                        <td>
                            <a asp-route-id="@flm.No" class="btn btn-block btn-dark" asp-action="Update">Edit</a>
                        </td>
                        <td>
                            <form asp-route-id="@flm.No" method="post" asp-action="Remove">
                                <input class="btn-warning btn btn-block" value="Remove" type="submit" />
                            </form>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="5">No movies found</td>
                </tr>
            }
        </table>
    </div>
</div>

NetCore-Docker-Easy/Views/Film/Update.cshtml
@model Film

@{
    ViewData["Title"] = "Modify a Movie";
}

<div class="row m-4">
    <div class="column">
        <h1 class="text-dark">Modify a Movie</h1>
    </div>
</div>

<div class="row m-4">
    <div class="row m-2">
        <div class="column col-3">
            <a class="btn btn-outline-info" asp-action="Index">Show all Movies</a>
        </div>
    </div>

    <div class="row m-2">
        <div class="column col-4">
            <form enctype="application/x-www-form-urlencoded" method="post">
                <div class="form-group m-2">
                    <label for="No">No.</label>
                    <input class="form-control" type="text" asp-for="No" id="No" readonly/>
                </div>
                <div class="form-group m-2">
                    <label for="MovieName">Movie Name</label>
                    <input class="form-control" type="text" asp-for="MovieName" id="MovieName"/>
                </div>
                <div class="form-group m-2">
                    <label for="ReleaseYear">Release Year</label>
                    <input class="form-control" type="number" asp-for="ReleaseYear" id="ReleaseYear"/>
                </div>
                <div class="row m-2">
                    <button class="btn btn-secondary" type="submit">Modify</button>
                </div>
            </form>
        </div>
    </div>
</div>

NetCore-Docker-Easy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="row m-4">
    <h1 class="text-dark">DotNet, SqlServer, SonarQube & Docker</h1>
    <p>Demo CRUD Web App, using .NET 6, Sql Server and SonarQube for testing Docker integration.</p>
    
    <h3 class="text-dark">Database (Sql Server instance)</h3>
    <p>Once you'll be running the docker container, the database will we exposed and accessible at `localhost,1440`</p>

    <h3 class="text-dark">SonarQube</h3>
    <p>
        The SonarQube dashboard will be listening at <a href="http://localhost:9000/" target="_blank">localhost:9000</a>.<br />
        Follow the local-section instructions for testing SonarQube using the cli-tool.<br />
        You'll find these instructions, with the correct token, in your local SonarQube Dashboard once you'll have configured the project.
    </p>
    <p>
</div>

<div class="row m-4">
    <div class="column col-3">
        <a class="btn btn-outline-dark" asp-area="" asp-controller="Film" asp-action="Index">Film Section (CRUD)</a>
    </div>
</div>

NetCore-Docker-Easy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCore_Docker_Easy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetCore_Docker_Easy.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCore_Docker_Easy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Film" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetCore_Docker_Easy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>